doctrine:
    dbal:
        default_connection: postgres12_db_3nf
        connections:
            postgres12_db_3nf:
                url: '%env(resolve:DATABASE_3NF_URL)%'
            postgres12_db_non_3nf:
                url: '%env(resolve:DATABASE_NON_3NF_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
