# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    memcached_session: '%env(json:MEMCACHED_SESSION)%'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Connection\Postgres3NF:
        arguments:
            $connection: '@doctrine.dbal.postgres12_db_3nf_connection'
    App\Connection\PostgresNon3NF:
        arguments:
            $connection: '@doctrine.dbal.postgres12_db_non_3nf_connection'

    session.memcached:
        class: Memcached
        arguments:
            $persistent_id: 'session_'
        calls:
            - [ addServers, [ '%memcached_session%' ]]
        public: true

    session.handler.memcached:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
        arguments: ['@session.memcached', { prefix: 'session_', expiretime: '604800‬' }]
